name: reviewdog
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest
      - run: git branch
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          tools: composer:v2
      - name: Composer update
        run: composer update
        working-directory: ./code
      - name: Resolve dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader
        working-directory: ./code
      - name: Run PHPstan
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./vendor/bin/phpstan analyse --level 0 ./app
        working-directory: ./code
      - run: php test.php
